import {
  DEFAULT_CODEX_MODEL,
  DEFAULT_CODEX_PERMISSION_MODE,
  DEFAULT_CODEX_REASONING_EFFORT,
  DEFAULT_CODEX_SERVICE_TIER,
  type AppState,
} from "../../shared/types";

export const emptyState: AppState = {
  baseFolder: "",
  projects: [],
  archivedProjects: [],
  activeProject: null,
  runtime: {
    ready: false,
    activeProjectId: null,
    activeChatId: null,
    activeTurnId: null,
    status: "Loading.",
    threadStatus: null,
    tokenUsage: null,
    pendingRequests: [],
    chats: [],
    showProjectChats: false,
  },
  codexSettings: {
    chatModel: null,
    chatReasoningEffort: null,
    chatServiceTier: DEFAULT_CODEX_SERVICE_TIER,
    chatPermissionMode: DEFAULT_CODEX_PERMISSION_MODE,
    nextTurnModel: null,
    nextTurnReasoningEffort: null,
    nextTurnServiceTier: null,
    nextTurnPermissionMode: null,
    activeTurnModel: null,
    activeTurnReasoningEffort: null,
    activeTurnServiceTier: null,
    activeTurnPermissionMode: null,
    defaultModel: DEFAULT_CODEX_MODEL,
    defaultReasoningEffort: DEFAULT_CODEX_REASONING_EFFORT,
    defaultServiceTier: DEFAULT_CODEX_SERVICE_TIER,
    defaultPermissionMode: DEFAULT_CODEX_PERMISSION_MODE,
    models: [],
  },
  realtime: {
    available: false,
    model: "gpt-realtime-2",
    voice: "marin",
    reasoningEffort: "low",
    reason: null,
    apiKeySource: null,
    apiKeyEncrypted: false,
  },
};
